// Phase A live source registry — ~20 US cities with rodent-tagged official data.
//
// Each entry is the smallest config the corresponding adapter needs to issue
// a real query. Endpoints, date fields, and rodent filters were verified
// against the live portals as of 2025-Q1. Confidence reflects how directly
// the dataset captures rodent activity vs. nests under a broader 311 bucket.

import { createArcgisSource } from "./adapters/arcgis";
import { createCkanSource } from "./adapters/ckan";
import { createOpen311Source } from "./adapters/open311";
import { createSocrataSource } from "./adapters/socrata";
import type { RodentActivitySource } from "./types";

export const phaseASources: RodentActivitySource[] = [
  // -------- Socrata --------
  createSocrataSource({
    id: "nyc-rodent-inspection",
    name: "NYC Rodent Inspection",
    owner: "NYC Department of Health and Mental Hygiene",
    placeId: "new-york-city",
    endpoint: "https://data.cityofnewyork.us/resource/p937-wjvj.json",
    url: "https://data.cityofnewyork.us/Health/Rodent-Inspection/p937-wjvj",
    dateField: "inspection_date",
    typeField: "result",
    whereClause: "result in('Rat Activity','Failed for Other R')",
    zipField: "zip_code",
    latField: "latitude",
    lngField: "longitude",
    confidence: "high",
    comparabilityNote: "Inspection-based — direct evidence, not complaint-driven.",
  }),
  createSocrataSource({
    id: "chicago-rodent-baiting",
    name: "Chicago Rodent Baiting Requests",
    owner: "City of Chicago",
    placeId: "chicago",
    endpoint: "https://data.cityofchicago.org/resource/v6vf-nfxy.json",
    url: "https://data.cityofchicago.org/Service-Requests/311-Service-Requests/v6vf-nfxy",
    dateField: "created_date",
    typeField: "sr_type",
    whereClause: "sr_type='Rodent Baiting/Rat Complaint'",
    zipField: "zip_code",
    latField: "latitude",
    lngField: "longitude",
    statusField: "status",
    confidence: "high",
    comparabilityNote: "Complaint-initiated, but uniformly tagged with a dedicated SR type.",
  }),
  createSocrataSource({
    id: "sf-311-rodent",
    name: "San Francisco 311 Rodent Cases",
    owner: "City and County of San Francisco",
    placeId: "san-francisco",
    endpoint: "https://data.sfgov.org/resource/vw6y-z8j6.json",
    url: "https://data.sfgov.org/City-Infrastructure/311-Cases/vw6y-z8j6",
    dateField: "requested_datetime",
    typeField: "service_subtype",
    whereClause: "service_subtype like '%Rodent%' OR service_subtype like '%Rat%'",
    latField: "lat",
    lngField: "long",
    statusField: "status_description",
    confidence: "medium",
    comparabilityNote: "Complaint-based subset of a broader 311 stream.",
  }),
  createSocrataSource({
    id: "oakland-311-rodent",
    name: "Oakland Call Center Service Requests",
    owner: "City of Oakland",
    placeId: "oakland",
    endpoint: "https://data.oaklandca.gov/resource/quth-gb8e.json",
    url: "https://data.oaklandca.gov/Infrastructure/Service-requests-received-by-the-Oakland-Call-Cent/quth-gb8e",
    dateField: "datetimeinit",
    typeField: "reqcategory",
    whereClause: "reqcategory like '%Rodent%' OR reqcategory like '%Rat%'",
    statusField: "status",
    confidence: "medium",
    comparabilityNote: "Complaint-based; geocoding completeness varies.",
  }),
  createSocrataSource({
    id: "seattle-find-it-rodent",
    name: "Seattle Find It Fix It — Rodents",
    owner: "City of Seattle",
    placeId: "seattle",
    endpoint: "https://data.seattle.gov/resource/p3i6-mdy7.json",
    url: "https://data.seattle.gov/Community-and-Culture/Find-It-Fix-It-Service-Requests/p3i6-mdy7",
    dateField: "created_date",
    typeField: "service_request_type",
    whereClause: "service_request_type like '%Rodent%'",
    latField: "latitude",
    lngField: "longitude",
    statusField: "status",
    confidence: "medium",
    comparabilityNote: "Complaint-based via Find It Fix It app — skews to digital users.",
  }),
  createSocrataSource({
    id: "la-myla311-rodent",
    name: "Los Angeles MyLA311 Rodent Calls",
    owner: "City of Los Angeles",
    placeId: "los-angeles",
    endpoint: "https://data.lacity.org/resource/rq3b-xjk8.json",
    url: "https://data.lacity.org/City-Infrastructure-Service-Requests/MyLA311-Service-Request-Data-2024/rq3b-xjk8",
    dateField: "createddate",
    typeField: "requesttype",
    whereClause: "requesttype like '%Rodent%' OR requesttype like '%Vermin%'",
    zipField: "zipcode",
    latField: "latitude",
    lngField: "longitude",
    statusField: "status",
    confidence: "medium",
    comparabilityNote: "Complaint-driven; high under-reporting in low-trust neighborhoods.",
  }),
  createSocrataSource({
    id: "austin-311-rodent",
    name: "Austin 311 Rodent / Rat Complaints",
    owner: "City of Austin",
    placeId: "austin",
    endpoint: "https://data.austintexas.gov/resource/xwdj-i9he.json",
    url: "https://data.austintexas.gov/City-Government/311-Unified-Data/xwdj-i9he",
    dateField: "created_date",
    typeField: "sr_type_desc",
    whereClause: "sr_type_desc like '%Rodent%' OR sr_type_desc like '%Rat%'",
    zipField: "sr_location_zip_code",
    latField: "latitude_coordinate",
    lngField: "longitude_coordinate",
    statusField: "sr_status",
    confidence: "medium",
    comparabilityNote: "Complaint-based; small relative volume vs. coastal peers.",
  }),
  createSocrataSource({
    id: "dallas-311-rodent",
    name: "Dallas 311 Rodent Complaints",
    owner: "City of Dallas",
    placeId: "dallas",
    endpoint: "https://www.dallasopendata.com/resource/qm6q-r2eq.json",
    url: "https://www.dallasopendata.com/dataset/qm6q-r2eq",
    dateField: "created_date",
    typeField: "service_request_type",
    whereClause: "service_request_type like '%Rodent%'",
    confidence: "medium",
    comparabilityNote: "Complaint-based; recent reorganization of SR taxonomy.",
  }),
  createSocrataSource({
    id: "kcmo-311-rodent",
    name: "Kansas City 311 Rodent Requests",
    owner: "City of Kansas City, MO",
    placeId: "kansas-city",
    endpoint: "https://data.kcmo.org/resource/7at3-sxhp.json",
    url: "https://data.kcmo.org/311/311-Call-Center-Service-Requests/7at3-sxhp",
    dateField: "creation_date",
    typeField: "request_type",
    whereClause: "request_type like '%Rodent%'",
    confidence: "low",
    comparabilityNote: "Small-volume; useful for trend but not absolute comparisons.",
  }),
  createSocrataSource({
    id: "baltimore-311-rodent",
    name: "Baltimore 311 Rat Rubout / Eradication",
    owner: "City of Baltimore",
    placeId: "baltimore",
    endpoint: "https://data.baltimorecity.gov/resource/9agw-sxsr.json",
    url: "https://data.baltimorecity.gov/datasets/311-customer-service-requests",
    dateField: "createddate",
    typeField: "srtype",
    whereClause: "srtype like '%Rat%' OR srtype like '%Rodent%'",
    zipField: "zipcode",
    latField: "latitude",
    lngField: "longitude",
    statusField: "srstatus",
    confidence: "high",
    comparabilityNote: "Dedicated 'Rat Rubout' SR type — high signal.",
  }),
  createSocrataSource({
    id: "denver-311-rodent",
    name: "Denver 311 Rodent Requests",
    owner: "City and County of Denver",
    placeId: "denver",
    endpoint: "https://data.denvergov.org/resource/k2g6-58e6.json",
    url: "https://data.denvergov.org/dataset/k2g6-58e6",
    dateField: "casecreated",
    typeField: "problemtype",
    whereClause: "problemtype like '%Rodent%'",
    confidence: "low",
    comparabilityNote: "Sparse rodent-tagged volume; treat trend cautiously.",
  }),
  createSocrataSource({
    id: "sandiego-311-rodent",
    name: "San Diego Get It Done — Pest",
    owner: "City of San Diego",
    placeId: "san-diego",
    endpoint: "https://seshat.datasd.org/get_it_done_311/get_it_done_requests_datasd_v1.json",
    url: "https://data.sandiego.gov/datasets/get-it-done-311/",
    dateField: "date_requested",
    typeField: "service_name",
    whereClause: "service_name like '%Pest%' OR service_name like '%Rodent%'",
    confidence: "low",
    comparabilityNote: "Pest category includes non-rodent reports; treat as upper bound.",
  }),

  // -------- ArcGIS --------
  createArcgisSource({
    id: "dc-311-rodent",
    name: "DC 311 Rodent Inspection & Treatment",
    owner: "District of Columbia",
    placeId: "washington-dc",
    featureLayerUrl:
      "https://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/ServiceRequests/MapServer/13",
    url: "https://opendata.dc.gov/datasets/DCGIS::311-city-service-requests-in-2025",
    dateField: "ADDDATE",
    typeField: "SERVICECODE",
    whereClause: "SERVICECODE = 'S0301'",
    zipField: "ZIPCODE",
    statusField: "SERVICEORDERSTATUS",
    confidence: "high",
    comparabilityNote: "Inspection + treatment dispatches — strong signal.",
  }),
  createArcgisSource({
    id: "atlanta-311-rodent",
    name: "Atlanta ATL311 Rodent Requests",
    owner: "City of Atlanta",
    placeId: "atlanta",
    featureLayerUrl:
      "https://services3.arcgis.com/Et5Qfajgiyosiw4d/arcgis/rest/services/ATL311_Service_Requests/FeatureServer/0",
    url: "https://gis.atlantaga.gov/atlgis/apps/dashboards/atl311",
    dateField: "createddate",
    typeField: "category",
    whereClause: "category LIKE '%Rodent%'",
    zipField: "zip",
    statusField: "status",
    confidence: "medium",
    comparabilityNote: "Complaint-based; coverage strongest in-perimeter.",
  }),
  createArcgisSource({
    id: "minneapolis-311-rodent",
    name: "Minneapolis 311 Rodent Reports",
    owner: "City of Minneapolis",
    placeId: "minneapolis",
    featureLayerUrl:
      "https://services.arcgis.com/afSMGVsC7QlRK1kZ/arcgis/rest/services/Minneapolis_311_Cases/FeatureServer/0",
    url: "https://opendata.minneapolismn.gov/datasets/minneapolis-311-cases",
    dateField: "OPENED",
    typeField: "CASETYPE",
    whereClause: "CASETYPE LIKE '%Rodent%'",
    statusField: "STATUS",
    confidence: "low",
    comparabilityNote: "Cold-climate baseline; volume sensitive to winter.",
  }),

  // -------- Open311 --------
  createOpen311Source({
    id: "boston-311-rodent",
    name: "Boston 311 Rodent Activity",
    owner: "City of Boston",
    placeId: "boston",
    endpoint: "https://311api.cityofboston.gov/open311/v2/requests.json",
    url: "https://data.boston.gov/dataset/311-service-requests",
    serviceCodes: ["4f3bf2f8e750846744000005", "4f3bf30be750846744000007"],
    confidence: "high",
    comparabilityNote: "Inspector-routed; 'Rodent Activity' is a dedicated code.",
  }),
  createOpen311Source({
    id: "cambridge-311-rodent",
    name: "Cambridge 311 Rodent Sightings",
    owner: "City of Cambridge, MA",
    placeId: "cambridge",
    endpoint: "https://commonwealthconnect.org/open311/v2/requests.json",
    url: "https://www.cambridgema.gov/Departments/publicworks/311",
    serviceCodes: ["4ffa9f2e6018277d3200008e"],
    jurisdictionId: "cambridgema.gov",
    confidence: "medium",
    comparabilityNote: "Smaller volume — pair with trend, not absolutes.",
  }),
  createOpen311Source({
    id: "somerville-311-rodent",
    name: "Somerville 311 Rodent Reports",
    owner: "City of Somerville, MA",
    placeId: "somerville",
    endpoint: "https://seeclickfix.com/open311/v2/requests.json",
    url: "https://www.somervillema.gov/departments/311",
    serviceCodes: ["3923"],
    jurisdictionId: "somervillema.gov",
    confidence: "low",
    comparabilityNote: "Routed via SeeClickFix — skews to engaged residents.",
  }),

  // -------- CKAN --------
  createCkanSource({
    id: "philly-311-rodent",
    name: "Philadelphia 311 Rodent Complaints",
    owner: "City of Philadelphia",
    placeId: "philadelphia",
    sqlEndpoint: "https://phl.carto.com/api/v2/sql",
    resourceId: "public_cases_fc",
    url: "https://www.opendataphilly.org/dataset/311-service-and-information-requests",
    dateField: "requested_datetime",
    typeField: "service_name",
    rodentTypeValues: ["Rodent Infestation"],
    zipField: "zipcode",
    latField: "lat",
    lngField: "lon",
    statusField: "status",
    confidence: "high",
    comparabilityNote: "Single 'Rodent Infestation' code — clean signal.",
  }),
  createCkanSource({
    id: "toronto-311-rodent",
    name: "Toronto 311 Rats & Rodents",
    owner: "City of Toronto",
    placeId: "toronto",
    sqlEndpoint:
      "https://ckan0.cf.opendata.inter.prod-toronto.ca/api/3/action/datastore_search_sql",
    resourceId: "311-service-requests-customer-initiated",
    url: "https://open.toronto.ca/dataset/311-service-requests-customer-initiated/",
    dateField: "Creation Date",
    typeField: "Service Request Type",
    rodentTypeValues: ["Rats and Mice"],
    confidence: "medium",
    comparabilityNote: "Out of US scope but listed for cross-border context.",
  }),
];
