/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyItKeepsComingBackRouteImport } from './routes/why-it-keeps-coming-back'
import { Route as WhatToExpectRouteImport } from './routes/what-to-expect'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as RodentRadarRouteImport } from './routes/rodent-radar'
import { Route as RodentFertilityControlRouteImport } from './routes/rodent-fertility-control'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as PaymentConfirmedRouteImport } from './routes/payment-confirmed'
import { Route as NjRodentViolationRouteImport } from './routes/nj-rodent-violation'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EvolveRodentBirthControlRouteImport } from './routes/evolve-rodent-birth-control'
import { Route as DohmhRodentViolationNycRouteImport } from './routes/dohmh-rodent-violation-nyc'
import { Route as DoesRatBirthControlWorkRouteImport } from './routes/does-rat-birth-control-work'
import { Route as ContrapestVsEvolveRouteImport } from './routes/contrapest-vs-evolve'
import { Route as ContrapestRouteImport } from './routes/contrapest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as VsWesternPestServicesRouteImport } from './routes/vs.western-pest-services'
import { Route as VsVikingPestControlRouteImport } from './routes/vs.viking-pest-control'
import { Route as VsTraditionalPestControlRouteImport } from './routes/vs.traditional-pest-control'
import { Route as VsSnapTrapsRouteImport } from './routes/vs.snap-traps'
import { Route as VsRatPoisonRouteImport } from './routes/vs.rat-poison'
import { Route as VsOrkinRouteImport } from './routes/vs.orkin'
import { Route as VsDiyRatBirthControlRouteImport } from './routes/vs.diy-rat-birth-control'
import { Route as VsBellEnvironmentalRouteImport } from './routes/vs.bell-environmental'
import { Route as VsAssuredEnvironmentsRouteImport } from './routes/vs.assured-environments'
import { Route as SolutionsRestaurantsRouteImport } from './routes/solutions.restaurants'
import { Route as SolutionsResidentialRouteImport } from './routes/solutions.residential'
import { Route as SolutionsPropertyManagersRouteImport } from './routes/solutions.property-managers'
import { Route as SolutionsMouseViolationsRouteImport } from './routes/solutions.mouse-violations'
import { Route as SolutionsHoasRouteImport } from './routes/solutions.hoas'
import { Route as SolutionsGhostKitchensRouteImport } from './routes/solutions.ghost-kitchens'
import { Route as SolutionsFoodStorageRouteImport } from './routes/solutions.food-storage'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as RodentRadarTermsRouteImport } from './routes/rodent-radar_.terms'
import { Route as RodentRadarRodentPopulationCalculatorRouteImport } from './routes/rodent-radar_.rodent-population-calculator'
import { Route as RodentRadarRatPressureMapRouteImport } from './routes/rodent-radar_.rat-pressure-map'
import { Route as RodentRadarHantavirusRiskCheckerRouteImport } from './routes/rodent-radar_.hantavirus-risk-checker'
import { Route as RodentRadarAttributionRouteImport } from './routes/rodent-radar_.attribution'
import { Route as ProductsStarterKitRouteImport } from './routes/products.starter-kit'
import { Route as ProductsRefillRouteImport } from './routes/products.refill'
import { Route as AreasAreaSlugRouteImport } from './routes/areas.$areaSlug'

const WhyItKeepsComingBackRoute = WhyItKeepsComingBackRouteImport.update({
  id: '/why-it-keeps-coming-back',
  path: '/why-it-keeps-coming-back',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatToExpectRoute = WhatToExpectRouteImport.update({
  id: '/what-to-expect',
  path: '/what-to-expect',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const RodentRadarRoute = RodentRadarRouteImport.update({
  id: '/rodent-radar',
  path: '/rodent-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const RodentFertilityControlRoute = RodentFertilityControlRouteImport.update({
  id: '/rodent-fertility-control',
  path: '/rodent-fertility-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentConfirmedRoute = PaymentConfirmedRouteImport.update({
  id: '/payment-confirmed',
  path: '/payment-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const NjRodentViolationRoute = NjRodentViolationRouteImport.update({
  id: '/nj-rodent-violation',
  path: '/nj-rodent-violation',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolveRodentBirthControlRoute =
  EvolveRodentBirthControlRouteImport.update({
    id: '/evolve-rodent-birth-control',
    path: '/evolve-rodent-birth-control',
    getParentRoute: () => rootRouteImport,
  } as any)
const DohmhRodentViolationNycRoute = DohmhRodentViolationNycRouteImport.update({
  id: '/dohmh-rodent-violation-nyc',
  path: '/dohmh-rodent-violation-nyc',
  getParentRoute: () => rootRouteImport,
} as any)
const DoesRatBirthControlWorkRoute = DoesRatBirthControlWorkRouteImport.update({
  id: '/does-rat-birth-control-work',
  path: '/does-rat-birth-control-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContrapestVsEvolveRoute = ContrapestVsEvolveRouteImport.update({
  id: '/contrapest-vs-evolve',
  path: '/contrapest-vs-evolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ContrapestRoute = ContrapestRouteImport.update({
  id: '/contrapest',
  path: '/contrapest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsWesternPestServicesRoute = VsWesternPestServicesRouteImport.update({
  id: '/vs/western-pest-services',
  path: '/vs/western-pest-services',
  getParentRoute: () => rootRouteImport,
} as any)
const VsVikingPestControlRoute = VsVikingPestControlRouteImport.update({
  id: '/vs/viking-pest-control',
  path: '/vs/viking-pest-control',
  getParentRoute: () => rootRouteImport,
} as any)
const VsTraditionalPestControlRoute =
  VsTraditionalPestControlRouteImport.update({
    id: '/vs/traditional-pest-control',
    path: '/vs/traditional-pest-control',
    getParentRoute: () => rootRouteImport,
  } as any)
const VsSnapTrapsRoute = VsSnapTrapsRouteImport.update({
  id: '/vs/snap-traps',
  path: '/vs/snap-traps',
  getParentRoute: () => rootRouteImport,
} as any)
const VsRatPoisonRoute = VsRatPoisonRouteImport.update({
  id: '/vs/rat-poison',
  path: '/vs/rat-poison',
  getParentRoute: () => rootRouteImport,
} as any)
const VsOrkinRoute = VsOrkinRouteImport.update({
  id: '/vs/orkin',
  path: '/vs/orkin',
  getParentRoute: () => rootRouteImport,
} as any)
const VsDiyRatBirthControlRoute = VsDiyRatBirthControlRouteImport.update({
  id: '/vs/diy-rat-birth-control',
  path: '/vs/diy-rat-birth-control',
  getParentRoute: () => rootRouteImport,
} as any)
const VsBellEnvironmentalRoute = VsBellEnvironmentalRouteImport.update({
  id: '/vs/bell-environmental',
  path: '/vs/bell-environmental',
  getParentRoute: () => rootRouteImport,
} as any)
const VsAssuredEnvironmentsRoute = VsAssuredEnvironmentsRouteImport.update({
  id: '/vs/assured-environments',
  path: '/vs/assured-environments',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRestaurantsRoute = SolutionsRestaurantsRouteImport.update({
  id: '/solutions/restaurants',
  path: '/solutions/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsResidentialRoute = SolutionsResidentialRouteImport.update({
  id: '/solutions/residential',
  path: '/solutions/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsPropertyManagersRoute =
  SolutionsPropertyManagersRouteImport.update({
    id: '/solutions/property-managers',
    path: '/solutions/property-managers',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsMouseViolationsRoute =
  SolutionsMouseViolationsRouteImport.update({
    id: '/solutions/mouse-violations',
    path: '/solutions/mouse-violations',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsHoasRoute = SolutionsHoasRouteImport.update({
  id: '/solutions/hoas',
  path: '/solutions/hoas',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsGhostKitchensRoute = SolutionsGhostKitchensRouteImport.update({
  id: '/solutions/ghost-kitchens',
  path: '/solutions/ghost-kitchens',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsFoodStorageRoute = SolutionsFoodStorageRouteImport.update({
  id: '/solutions/food-storage',
  path: '/solutions/food-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RodentRadarTermsRoute = RodentRadarTermsRouteImport.update({
  id: '/rodent-radar_/terms',
  path: '/rodent-radar/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RodentRadarRodentPopulationCalculatorRoute =
  RodentRadarRodentPopulationCalculatorRouteImport.update({
    id: '/rodent-radar_/rodent-population-calculator',
    path: '/rodent-radar/rodent-population-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const RodentRadarRatPressureMapRoute =
  RodentRadarRatPressureMapRouteImport.update({
    id: '/rodent-radar_/rat-pressure-map',
    path: '/rodent-radar/rat-pressure-map',
    getParentRoute: () => rootRouteImport,
  } as any)
const RodentRadarHantavirusRiskCheckerRoute =
  RodentRadarHantavirusRiskCheckerRouteImport.update({
    id: '/rodent-radar_/hantavirus-risk-checker',
    path: '/rodent-radar/hantavirus-risk-checker',
    getParentRoute: () => rootRouteImport,
  } as any)
const RodentRadarAttributionRoute = RodentRadarAttributionRouteImport.update({
  id: '/rodent-radar_/attribution',
  path: '/rodent-radar/attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsStarterKitRoute = ProductsStarterKitRouteImport.update({
  id: '/products/starter-kit',
  path: '/products/starter-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRefillRoute = ProductsRefillRouteImport.update({
  id: '/products/refill',
  path: '/products/refill',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAreaSlugRoute = AreasAreaSlugRouteImport.update({
  id: '/areas/$areaSlug',
  path: '/areas/$areaSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contrapest': typeof ContrapestRoute
  '/contrapest-vs-evolve': typeof ContrapestVsEvolveRoute
  '/does-rat-birth-control-work': typeof DoesRatBirthControlWorkRoute
  '/dohmh-rodent-violation-nyc': typeof DohmhRodentViolationNycRoute
  '/evolve-rodent-birth-control': typeof EvolveRodentBirthControlRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/nj-rodent-violation': typeof NjRodentViolationRoute
  '/payment-confirmed': typeof PaymentConfirmedRoute
  '/questions': typeof QuestionsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/rodent-fertility-control': typeof RodentFertilityControlRoute
  '/rodent-radar': typeof RodentRadarRoute
  '/thank-you': typeof ThankYouRoute
  '/what-to-expect': typeof WhatToExpectRoute
  '/why-it-keeps-coming-back': typeof WhyItKeepsComingBackRoute
  '/areas/$areaSlug': typeof AreasAreaSlugRoute
  '/products/refill': typeof ProductsRefillRoute
  '/products/starter-kit': typeof ProductsStarterKitRoute
  '/rodent-radar/attribution': typeof RodentRadarAttributionRoute
  '/rodent-radar/hantavirus-risk-checker': typeof RodentRadarHantavirusRiskCheckerRoute
  '/rodent-radar/rat-pressure-map': typeof RodentRadarRatPressureMapRoute
  '/rodent-radar/rodent-population-calculator': typeof RodentRadarRodentPopulationCalculatorRoute
  '/rodent-radar/terms': typeof RodentRadarTermsRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/food-storage': typeof SolutionsFoodStorageRoute
  '/solutions/ghost-kitchens': typeof SolutionsGhostKitchensRoute
  '/solutions/hoas': typeof SolutionsHoasRoute
  '/solutions/mouse-violations': typeof SolutionsMouseViolationsRoute
  '/solutions/property-managers': typeof SolutionsPropertyManagersRoute
  '/solutions/residential': typeof SolutionsResidentialRoute
  '/solutions/restaurants': typeof SolutionsRestaurantsRoute
  '/vs/assured-environments': typeof VsAssuredEnvironmentsRoute
  '/vs/bell-environmental': typeof VsBellEnvironmentalRoute
  '/vs/diy-rat-birth-control': typeof VsDiyRatBirthControlRoute
  '/vs/orkin': typeof VsOrkinRoute
  '/vs/rat-poison': typeof VsRatPoisonRoute
  '/vs/snap-traps': typeof VsSnapTrapsRoute
  '/vs/traditional-pest-control': typeof VsTraditionalPestControlRoute
  '/vs/viking-pest-control': typeof VsVikingPestControlRoute
  '/vs/western-pest-services': typeof VsWesternPestServicesRoute
  '/areas/': typeof AreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contrapest': typeof ContrapestRoute
  '/contrapest-vs-evolve': typeof ContrapestVsEvolveRoute
  '/does-rat-birth-control-work': typeof DoesRatBirthControlWorkRoute
  '/dohmh-rodent-violation-nyc': typeof DohmhRodentViolationNycRoute
  '/evolve-rodent-birth-control': typeof EvolveRodentBirthControlRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/nj-rodent-violation': typeof NjRodentViolationRoute
  '/payment-confirmed': typeof PaymentConfirmedRoute
  '/questions': typeof QuestionsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/rodent-fertility-control': typeof RodentFertilityControlRoute
  '/rodent-radar': typeof RodentRadarRoute
  '/thank-you': typeof ThankYouRoute
  '/what-to-expect': typeof WhatToExpectRoute
  '/why-it-keeps-coming-back': typeof WhyItKeepsComingBackRoute
  '/areas/$areaSlug': typeof AreasAreaSlugRoute
  '/products/refill': typeof ProductsRefillRoute
  '/products/starter-kit': typeof ProductsStarterKitRoute
  '/rodent-radar/attribution': typeof RodentRadarAttributionRoute
  '/rodent-radar/hantavirus-risk-checker': typeof RodentRadarHantavirusRiskCheckerRoute
  '/rodent-radar/rat-pressure-map': typeof RodentRadarRatPressureMapRoute
  '/rodent-radar/rodent-population-calculator': typeof RodentRadarRodentPopulationCalculatorRoute
  '/rodent-radar/terms': typeof RodentRadarTermsRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/food-storage': typeof SolutionsFoodStorageRoute
  '/solutions/ghost-kitchens': typeof SolutionsGhostKitchensRoute
  '/solutions/hoas': typeof SolutionsHoasRoute
  '/solutions/mouse-violations': typeof SolutionsMouseViolationsRoute
  '/solutions/property-managers': typeof SolutionsPropertyManagersRoute
  '/solutions/residential': typeof SolutionsResidentialRoute
  '/solutions/restaurants': typeof SolutionsRestaurantsRoute
  '/vs/assured-environments': typeof VsAssuredEnvironmentsRoute
  '/vs/bell-environmental': typeof VsBellEnvironmentalRoute
  '/vs/diy-rat-birth-control': typeof VsDiyRatBirthControlRoute
  '/vs/orkin': typeof VsOrkinRoute
  '/vs/rat-poison': typeof VsRatPoisonRoute
  '/vs/snap-traps': typeof VsSnapTrapsRoute
  '/vs/traditional-pest-control': typeof VsTraditionalPestControlRoute
  '/vs/viking-pest-control': typeof VsVikingPestControlRoute
  '/vs/western-pest-services': typeof VsWesternPestServicesRoute
  '/areas': typeof AreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contrapest': typeof ContrapestRoute
  '/contrapest-vs-evolve': typeof ContrapestVsEvolveRoute
  '/does-rat-birth-control-work': typeof DoesRatBirthControlWorkRoute
  '/dohmh-rodent-violation-nyc': typeof DohmhRodentViolationNycRoute
  '/evolve-rodent-birth-control': typeof EvolveRodentBirthControlRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/nj-rodent-violation': typeof NjRodentViolationRoute
  '/payment-confirmed': typeof PaymentConfirmedRoute
  '/questions': typeof QuestionsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/rodent-fertility-control': typeof RodentFertilityControlRoute
  '/rodent-radar': typeof RodentRadarRoute
  '/thank-you': typeof ThankYouRoute
  '/what-to-expect': typeof WhatToExpectRoute
  '/why-it-keeps-coming-back': typeof WhyItKeepsComingBackRoute
  '/areas/$areaSlug': typeof AreasAreaSlugRoute
  '/products/refill': typeof ProductsRefillRoute
  '/products/starter-kit': typeof ProductsStarterKitRoute
  '/rodent-radar_/attribution': typeof RodentRadarAttributionRoute
  '/rodent-radar_/hantavirus-risk-checker': typeof RodentRadarHantavirusRiskCheckerRoute
  '/rodent-radar_/rat-pressure-map': typeof RodentRadarRatPressureMapRoute
  '/rodent-radar_/rodent-population-calculator': typeof RodentRadarRodentPopulationCalculatorRoute
  '/rodent-radar_/terms': typeof RodentRadarTermsRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/food-storage': typeof SolutionsFoodStorageRoute
  '/solutions/ghost-kitchens': typeof SolutionsGhostKitchensRoute
  '/solutions/hoas': typeof SolutionsHoasRoute
  '/solutions/mouse-violations': typeof SolutionsMouseViolationsRoute
  '/solutions/property-managers': typeof SolutionsPropertyManagersRoute
  '/solutions/residential': typeof SolutionsResidentialRoute
  '/solutions/restaurants': typeof SolutionsRestaurantsRoute
  '/vs/assured-environments': typeof VsAssuredEnvironmentsRoute
  '/vs/bell-environmental': typeof VsBellEnvironmentalRoute
  '/vs/diy-rat-birth-control': typeof VsDiyRatBirthControlRoute
  '/vs/orkin': typeof VsOrkinRoute
  '/vs/rat-poison': typeof VsRatPoisonRoute
  '/vs/snap-traps': typeof VsSnapTrapsRoute
  '/vs/traditional-pest-control': typeof VsTraditionalPestControlRoute
  '/vs/viking-pest-control': typeof VsVikingPestControlRoute
  '/vs/western-pest-services': typeof VsWesternPestServicesRoute
  '/areas/': typeof AreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contrapest'
    | '/contrapest-vs-evolve'
    | '/does-rat-birth-control-work'
    | '/dohmh-rodent-violation-nyc'
    | '/evolve-rodent-birth-control'
    | '/faq'
    | '/get-started'
    | '/how-it-works'
    | '/nj-rodent-violation'
    | '/payment-confirmed'
    | '/questions'
    | '/resources'
    | '/results'
    | '/rodent-fertility-control'
    | '/rodent-radar'
    | '/thank-you'
    | '/what-to-expect'
    | '/why-it-keeps-coming-back'
    | '/areas/$areaSlug'
    | '/products/refill'
    | '/products/starter-kit'
    | '/rodent-radar/attribution'
    | '/rodent-radar/hantavirus-risk-checker'
    | '/rodent-radar/rat-pressure-map'
    | '/rodent-radar/rodent-population-calculator'
    | '/rodent-radar/terms'
    | '/solutions/$slug'
    | '/solutions/food-storage'
    | '/solutions/ghost-kitchens'
    | '/solutions/hoas'
    | '/solutions/mouse-violations'
    | '/solutions/property-managers'
    | '/solutions/residential'
    | '/solutions/restaurants'
    | '/vs/assured-environments'
    | '/vs/bell-environmental'
    | '/vs/diy-rat-birth-control'
    | '/vs/orkin'
    | '/vs/rat-poison'
    | '/vs/snap-traps'
    | '/vs/traditional-pest-control'
    | '/vs/viking-pest-control'
    | '/vs/western-pest-services'
    | '/areas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contrapest'
    | '/contrapest-vs-evolve'
    | '/does-rat-birth-control-work'
    | '/dohmh-rodent-violation-nyc'
    | '/evolve-rodent-birth-control'
    | '/faq'
    | '/get-started'
    | '/how-it-works'
    | '/nj-rodent-violation'
    | '/payment-confirmed'
    | '/questions'
    | '/resources'
    | '/results'
    | '/rodent-fertility-control'
    | '/rodent-radar'
    | '/thank-you'
    | '/what-to-expect'
    | '/why-it-keeps-coming-back'
    | '/areas/$areaSlug'
    | '/products/refill'
    | '/products/starter-kit'
    | '/rodent-radar/attribution'
    | '/rodent-radar/hantavirus-risk-checker'
    | '/rodent-radar/rat-pressure-map'
    | '/rodent-radar/rodent-population-calculator'
    | '/rodent-radar/terms'
    | '/solutions/$slug'
    | '/solutions/food-storage'
    | '/solutions/ghost-kitchens'
    | '/solutions/hoas'
    | '/solutions/mouse-violations'
    | '/solutions/property-managers'
    | '/solutions/residential'
    | '/solutions/restaurants'
    | '/vs/assured-environments'
    | '/vs/bell-environmental'
    | '/vs/diy-rat-birth-control'
    | '/vs/orkin'
    | '/vs/rat-poison'
    | '/vs/snap-traps'
    | '/vs/traditional-pest-control'
    | '/vs/viking-pest-control'
    | '/vs/western-pest-services'
    | '/areas'
  id:
    | '__root__'
    | '/'
    | '/contrapest'
    | '/contrapest-vs-evolve'
    | '/does-rat-birth-control-work'
    | '/dohmh-rodent-violation-nyc'
    | '/evolve-rodent-birth-control'
    | '/faq'
    | '/get-started'
    | '/how-it-works'
    | '/nj-rodent-violation'
    | '/payment-confirmed'
    | '/questions'
    | '/resources'
    | '/results'
    | '/rodent-fertility-control'
    | '/rodent-radar'
    | '/thank-you'
    | '/what-to-expect'
    | '/why-it-keeps-coming-back'
    | '/areas/$areaSlug'
    | '/products/refill'
    | '/products/starter-kit'
    | '/rodent-radar_/attribution'
    | '/rodent-radar_/hantavirus-risk-checker'
    | '/rodent-radar_/rat-pressure-map'
    | '/rodent-radar_/rodent-population-calculator'
    | '/rodent-radar_/terms'
    | '/solutions/$slug'
    | '/solutions/food-storage'
    | '/solutions/ghost-kitchens'
    | '/solutions/hoas'
    | '/solutions/mouse-violations'
    | '/solutions/property-managers'
    | '/solutions/residential'
    | '/solutions/restaurants'
    | '/vs/assured-environments'
    | '/vs/bell-environmental'
    | '/vs/diy-rat-birth-control'
    | '/vs/orkin'
    | '/vs/rat-poison'
    | '/vs/snap-traps'
    | '/vs/traditional-pest-control'
    | '/vs/viking-pest-control'
    | '/vs/western-pest-services'
    | '/areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContrapestRoute: typeof ContrapestRoute
  ContrapestVsEvolveRoute: typeof ContrapestVsEvolveRoute
  DoesRatBirthControlWorkRoute: typeof DoesRatBirthControlWorkRoute
  DohmhRodentViolationNycRoute: typeof DohmhRodentViolationNycRoute
  EvolveRodentBirthControlRoute: typeof EvolveRodentBirthControlRoute
  FaqRoute: typeof FaqRoute
  GetStartedRoute: typeof GetStartedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  NjRodentViolationRoute: typeof NjRodentViolationRoute
  PaymentConfirmedRoute: typeof PaymentConfirmedRoute
  QuestionsRoute: typeof QuestionsRoute
  ResourcesRoute: typeof ResourcesRoute
  ResultsRoute: typeof ResultsRoute
  RodentFertilityControlRoute: typeof RodentFertilityControlRoute
  RodentRadarRoute: typeof RodentRadarRoute
  ThankYouRoute: typeof ThankYouRoute
  WhatToExpectRoute: typeof WhatToExpectRoute
  WhyItKeepsComingBackRoute: typeof WhyItKeepsComingBackRoute
  AreasAreaSlugRoute: typeof AreasAreaSlugRoute
  ProductsRefillRoute: typeof ProductsRefillRoute
  ProductsStarterKitRoute: typeof ProductsStarterKitRoute
  RodentRadarAttributionRoute: typeof RodentRadarAttributionRoute
  RodentRadarHantavirusRiskCheckerRoute: typeof RodentRadarHantavirusRiskCheckerRoute
  RodentRadarRatPressureMapRoute: typeof RodentRadarRatPressureMapRoute
  RodentRadarRodentPopulationCalculatorRoute: typeof RodentRadarRodentPopulationCalculatorRoute
  RodentRadarTermsRoute: typeof RodentRadarTermsRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SolutionsFoodStorageRoute: typeof SolutionsFoodStorageRoute
  SolutionsGhostKitchensRoute: typeof SolutionsGhostKitchensRoute
  SolutionsHoasRoute: typeof SolutionsHoasRoute
  SolutionsMouseViolationsRoute: typeof SolutionsMouseViolationsRoute
  SolutionsPropertyManagersRoute: typeof SolutionsPropertyManagersRoute
  SolutionsResidentialRoute: typeof SolutionsResidentialRoute
  SolutionsRestaurantsRoute: typeof SolutionsRestaurantsRoute
  VsAssuredEnvironmentsRoute: typeof VsAssuredEnvironmentsRoute
  VsBellEnvironmentalRoute: typeof VsBellEnvironmentalRoute
  VsDiyRatBirthControlRoute: typeof VsDiyRatBirthControlRoute
  VsOrkinRoute: typeof VsOrkinRoute
  VsRatPoisonRoute: typeof VsRatPoisonRoute
  VsSnapTrapsRoute: typeof VsSnapTrapsRoute
  VsTraditionalPestControlRoute: typeof VsTraditionalPestControlRoute
  VsVikingPestControlRoute: typeof VsVikingPestControlRoute
  VsWesternPestServicesRoute: typeof VsWesternPestServicesRoute
  AreasIndexRoute: typeof AreasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-it-keeps-coming-back': {
      id: '/why-it-keeps-coming-back'
      path: '/why-it-keeps-coming-back'
      fullPath: '/why-it-keeps-coming-back'
      preLoaderRoute: typeof WhyItKeepsComingBackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-to-expect': {
      id: '/what-to-expect'
      path: '/what-to-expect'
      fullPath: '/what-to-expect'
      preLoaderRoute: typeof WhatToExpectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rodent-radar': {
      id: '/rodent-radar'
      path: '/rodent-radar'
      fullPath: '/rodent-radar'
      preLoaderRoute: typeof RodentRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rodent-fertility-control': {
      id: '/rodent-fertility-control'
      path: '/rodent-fertility-control'
      fullPath: '/rodent-fertility-control'
      preLoaderRoute: typeof RodentFertilityControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-confirmed': {
      id: '/payment-confirmed'
      path: '/payment-confirmed'
      fullPath: '/payment-confirmed'
      preLoaderRoute: typeof PaymentConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nj-rodent-violation': {
      id: '/nj-rodent-violation'
      path: '/nj-rodent-violation'
      fullPath: '/nj-rodent-violation'
      preLoaderRoute: typeof NjRodentViolationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolve-rodent-birth-control': {
      id: '/evolve-rodent-birth-control'
      path: '/evolve-rodent-birth-control'
      fullPath: '/evolve-rodent-birth-control'
      preLoaderRoute: typeof EvolveRodentBirthControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dohmh-rodent-violation-nyc': {
      id: '/dohmh-rodent-violation-nyc'
      path: '/dohmh-rodent-violation-nyc'
      fullPath: '/dohmh-rodent-violation-nyc'
      preLoaderRoute: typeof DohmhRodentViolationNycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/does-rat-birth-control-work': {
      id: '/does-rat-birth-control-work'
      path: '/does-rat-birth-control-work'
      fullPath: '/does-rat-birth-control-work'
      preLoaderRoute: typeof DoesRatBirthControlWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrapest-vs-evolve': {
      id: '/contrapest-vs-evolve'
      path: '/contrapest-vs-evolve'
      fullPath: '/contrapest-vs-evolve'
      preLoaderRoute: typeof ContrapestVsEvolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrapest': {
      id: '/contrapest'
      path: '/contrapest'
      fullPath: '/contrapest'
      preLoaderRoute: typeof ContrapestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/western-pest-services': {
      id: '/vs/western-pest-services'
      path: '/vs/western-pest-services'
      fullPath: '/vs/western-pest-services'
      preLoaderRoute: typeof VsWesternPestServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/viking-pest-control': {
      id: '/vs/viking-pest-control'
      path: '/vs/viking-pest-control'
      fullPath: '/vs/viking-pest-control'
      preLoaderRoute: typeof VsVikingPestControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/traditional-pest-control': {
      id: '/vs/traditional-pest-control'
      path: '/vs/traditional-pest-control'
      fullPath: '/vs/traditional-pest-control'
      preLoaderRoute: typeof VsTraditionalPestControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/snap-traps': {
      id: '/vs/snap-traps'
      path: '/vs/snap-traps'
      fullPath: '/vs/snap-traps'
      preLoaderRoute: typeof VsSnapTrapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/rat-poison': {
      id: '/vs/rat-poison'
      path: '/vs/rat-poison'
      fullPath: '/vs/rat-poison'
      preLoaderRoute: typeof VsRatPoisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/orkin': {
      id: '/vs/orkin'
      path: '/vs/orkin'
      fullPath: '/vs/orkin'
      preLoaderRoute: typeof VsOrkinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/diy-rat-birth-control': {
      id: '/vs/diy-rat-birth-control'
      path: '/vs/diy-rat-birth-control'
      fullPath: '/vs/diy-rat-birth-control'
      preLoaderRoute: typeof VsDiyRatBirthControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/bell-environmental': {
      id: '/vs/bell-environmental'
      path: '/vs/bell-environmental'
      fullPath: '/vs/bell-environmental'
      preLoaderRoute: typeof VsBellEnvironmentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/assured-environments': {
      id: '/vs/assured-environments'
      path: '/vs/assured-environments'
      fullPath: '/vs/assured-environments'
      preLoaderRoute: typeof VsAssuredEnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/restaurants': {
      id: '/solutions/restaurants'
      path: '/solutions/restaurants'
      fullPath: '/solutions/restaurants'
      preLoaderRoute: typeof SolutionsRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/residential': {
      id: '/solutions/residential'
      path: '/solutions/residential'
      fullPath: '/solutions/residential'
      preLoaderRoute: typeof SolutionsResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/property-managers': {
      id: '/solutions/property-managers'
      path: '/solutions/property-managers'
      fullPath: '/solutions/property-managers'
      preLoaderRoute: typeof SolutionsPropertyManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/mouse-violations': {
      id: '/solutions/mouse-violations'
      path: '/solutions/mouse-violations'
      fullPath: '/solutions/mouse-violations'
      preLoaderRoute: typeof SolutionsMouseViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/hoas': {
      id: '/solutions/hoas'
      path: '/solutions/hoas'
      fullPath: '/solutions/hoas'
      preLoaderRoute: typeof SolutionsHoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ghost-kitchens': {
      id: '/solutions/ghost-kitchens'
      path: '/solutions/ghost-kitchens'
      fullPath: '/solutions/ghost-kitchens'
      preLoaderRoute: typeof SolutionsGhostKitchensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/food-storage': {
      id: '/solutions/food-storage'
      path: '/solutions/food-storage'
      fullPath: '/solutions/food-storage'
      preLoaderRoute: typeof SolutionsFoodStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rodent-radar_/terms': {
      id: '/rodent-radar_/terms'
      path: '/rodent-radar/terms'
      fullPath: '/rodent-radar/terms'
      preLoaderRoute: typeof RodentRadarTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rodent-radar_/rodent-population-calculator': {
      id: '/rodent-radar_/rodent-population-calculator'
      path: '/rodent-radar/rodent-population-calculator'
      fullPath: '/rodent-radar/rodent-population-calculator'
      preLoaderRoute: typeof RodentRadarRodentPopulationCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rodent-radar_/rat-pressure-map': {
      id: '/rodent-radar_/rat-pressure-map'
      path: '/rodent-radar/rat-pressure-map'
      fullPath: '/rodent-radar/rat-pressure-map'
      preLoaderRoute: typeof RodentRadarRatPressureMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rodent-radar_/hantavirus-risk-checker': {
      id: '/rodent-radar_/hantavirus-risk-checker'
      path: '/rodent-radar/hantavirus-risk-checker'
      fullPath: '/rodent-radar/hantavirus-risk-checker'
      preLoaderRoute: typeof RodentRadarHantavirusRiskCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rodent-radar_/attribution': {
      id: '/rodent-radar_/attribution'
      path: '/rodent-radar/attribution'
      fullPath: '/rodent-radar/attribution'
      preLoaderRoute: typeof RodentRadarAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/starter-kit': {
      id: '/products/starter-kit'
      path: '/products/starter-kit'
      fullPath: '/products/starter-kit'
      preLoaderRoute: typeof ProductsStarterKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/refill': {
      id: '/products/refill'
      path: '/products/refill'
      fullPath: '/products/refill'
      preLoaderRoute: typeof ProductsRefillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$areaSlug': {
      id: '/areas/$areaSlug'
      path: '/areas/$areaSlug'
      fullPath: '/areas/$areaSlug'
      preLoaderRoute: typeof AreasAreaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContrapestRoute: ContrapestRoute,
  ContrapestVsEvolveRoute: ContrapestVsEvolveRoute,
  DoesRatBirthControlWorkRoute: DoesRatBirthControlWorkRoute,
  DohmhRodentViolationNycRoute: DohmhRodentViolationNycRoute,
  EvolveRodentBirthControlRoute: EvolveRodentBirthControlRoute,
  FaqRoute: FaqRoute,
  GetStartedRoute: GetStartedRoute,
  HowItWorksRoute: HowItWorksRoute,
  NjRodentViolationRoute: NjRodentViolationRoute,
  PaymentConfirmedRoute: PaymentConfirmedRoute,
  QuestionsRoute: QuestionsRoute,
  ResourcesRoute: ResourcesRoute,
  ResultsRoute: ResultsRoute,
  RodentFertilityControlRoute: RodentFertilityControlRoute,
  RodentRadarRoute: RodentRadarRoute,
  ThankYouRoute: ThankYouRoute,
  WhatToExpectRoute: WhatToExpectRoute,
  WhyItKeepsComingBackRoute: WhyItKeepsComingBackRoute,
  AreasAreaSlugRoute: AreasAreaSlugRoute,
  ProductsRefillRoute: ProductsRefillRoute,
  ProductsStarterKitRoute: ProductsStarterKitRoute,
  RodentRadarAttributionRoute: RodentRadarAttributionRoute,
  RodentRadarHantavirusRiskCheckerRoute: RodentRadarHantavirusRiskCheckerRoute,
  RodentRadarRatPressureMapRoute: RodentRadarRatPressureMapRoute,
  RodentRadarRodentPopulationCalculatorRoute:
    RodentRadarRodentPopulationCalculatorRoute,
  RodentRadarTermsRoute: RodentRadarTermsRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  SolutionsFoodStorageRoute: SolutionsFoodStorageRoute,
  SolutionsGhostKitchensRoute: SolutionsGhostKitchensRoute,
  SolutionsHoasRoute: SolutionsHoasRoute,
  SolutionsMouseViolationsRoute: SolutionsMouseViolationsRoute,
  SolutionsPropertyManagersRoute: SolutionsPropertyManagersRoute,
  SolutionsResidentialRoute: SolutionsResidentialRoute,
  SolutionsRestaurantsRoute: SolutionsRestaurantsRoute,
  VsAssuredEnvironmentsRoute: VsAssuredEnvironmentsRoute,
  VsBellEnvironmentalRoute: VsBellEnvironmentalRoute,
  VsDiyRatBirthControlRoute: VsDiyRatBirthControlRoute,
  VsOrkinRoute: VsOrkinRoute,
  VsRatPoisonRoute: VsRatPoisonRoute,
  VsSnapTrapsRoute: VsSnapTrapsRoute,
  VsTraditionalPestControlRoute: VsTraditionalPestControlRoute,
  VsVikingPestControlRoute: VsVikingPestControlRoute,
  VsWesternPestServicesRoute: VsWesternPestServicesRoute,
  AreasIndexRoute: AreasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
