/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyItKeepsComingBackRouteImport } from './routes/why-it-keeps-coming-back'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsRestaurantsRouteImport } from './routes/solutions.restaurants'
import { Route as SolutionsResidentialRouteImport } from './routes/solutions.residential'
import { Route as SolutionsPropertyManagersRouteImport } from './routes/solutions.property-managers'
import { Route as SolutionsMouseViolationsRouteImport } from './routes/solutions.mouse-violations'
import { Route as SolutionsHoasRouteImport } from './routes/solutions.hoas'
import { Route as SolutionsGhostKitchensRouteImport } from './routes/solutions.ghost-kitchens'
import { Route as SolutionsFoodStorageRouteImport } from './routes/solutions.food-storage'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as AreasAreaSlugRouteImport } from './routes/areas.$areaSlug'

const WhyItKeepsComingBackRoute = WhyItKeepsComingBackRouteImport.update({
  id: '/why-it-keeps-coming-back',
  path: '/why-it-keeps-coming-back',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRestaurantsRoute = SolutionsRestaurantsRouteImport.update({
  id: '/solutions/restaurants',
  path: '/solutions/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsResidentialRoute = SolutionsResidentialRouteImport.update({
  id: '/solutions/residential',
  path: '/solutions/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsPropertyManagersRoute =
  SolutionsPropertyManagersRouteImport.update({
    id: '/solutions/property-managers',
    path: '/solutions/property-managers',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsMouseViolationsRoute =
  SolutionsMouseViolationsRouteImport.update({
    id: '/solutions/mouse-violations',
    path: '/solutions/mouse-violations',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsHoasRoute = SolutionsHoasRouteImport.update({
  id: '/solutions/hoas',
  path: '/solutions/hoas',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsGhostKitchensRoute = SolutionsGhostKitchensRouteImport.update({
  id: '/solutions/ghost-kitchens',
  path: '/solutions/ghost-kitchens',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsFoodStorageRoute = SolutionsFoodStorageRouteImport.update({
  id: '/solutions/food-storage',
  path: '/solutions/food-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAreaSlugRoute = AreasAreaSlugRouteImport.update({
  id: '/areas/$areaSlug',
  path: '/areas/$areaSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/why-it-keeps-coming-back': typeof WhyItKeepsComingBackRoute
  '/areas/$areaSlug': typeof AreasAreaSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/food-storage': typeof SolutionsFoodStorageRoute
  '/solutions/ghost-kitchens': typeof SolutionsGhostKitchensRoute
  '/solutions/hoas': typeof SolutionsHoasRoute
  '/solutions/mouse-violations': typeof SolutionsMouseViolationsRoute
  '/solutions/property-managers': typeof SolutionsPropertyManagersRoute
  '/solutions/residential': typeof SolutionsResidentialRoute
  '/solutions/restaurants': typeof SolutionsRestaurantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/why-it-keeps-coming-back': typeof WhyItKeepsComingBackRoute
  '/areas/$areaSlug': typeof AreasAreaSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/food-storage': typeof SolutionsFoodStorageRoute
  '/solutions/ghost-kitchens': typeof SolutionsGhostKitchensRoute
  '/solutions/hoas': typeof SolutionsHoasRoute
  '/solutions/mouse-violations': typeof SolutionsMouseViolationsRoute
  '/solutions/property-managers': typeof SolutionsPropertyManagersRoute
  '/solutions/residential': typeof SolutionsResidentialRoute
  '/solutions/restaurants': typeof SolutionsRestaurantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/why-it-keeps-coming-back': typeof WhyItKeepsComingBackRoute
  '/areas/$areaSlug': typeof AreasAreaSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/food-storage': typeof SolutionsFoodStorageRoute
  '/solutions/ghost-kitchens': typeof SolutionsGhostKitchensRoute
  '/solutions/hoas': typeof SolutionsHoasRoute
  '/solutions/mouse-violations': typeof SolutionsMouseViolationsRoute
  '/solutions/property-managers': typeof SolutionsPropertyManagersRoute
  '/solutions/residential': typeof SolutionsResidentialRoute
  '/solutions/restaurants': typeof SolutionsRestaurantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/get-started'
    | '/resources'
    | '/results'
    | '/why-it-keeps-coming-back'
    | '/areas/$areaSlug'
    | '/solutions/$slug'
    | '/solutions/food-storage'
    | '/solutions/ghost-kitchens'
    | '/solutions/hoas'
    | '/solutions/mouse-violations'
    | '/solutions/property-managers'
    | '/solutions/residential'
    | '/solutions/restaurants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/get-started'
    | '/resources'
    | '/results'
    | '/why-it-keeps-coming-back'
    | '/areas/$areaSlug'
    | '/solutions/$slug'
    | '/solutions/food-storage'
    | '/solutions/ghost-kitchens'
    | '/solutions/hoas'
    | '/solutions/mouse-violations'
    | '/solutions/property-managers'
    | '/solutions/residential'
    | '/solutions/restaurants'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/get-started'
    | '/resources'
    | '/results'
    | '/why-it-keeps-coming-back'
    | '/areas/$areaSlug'
    | '/solutions/$slug'
    | '/solutions/food-storage'
    | '/solutions/ghost-kitchens'
    | '/solutions/hoas'
    | '/solutions/mouse-violations'
    | '/solutions/property-managers'
    | '/solutions/residential'
    | '/solutions/restaurants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  GetStartedRoute: typeof GetStartedRoute
  ResourcesRoute: typeof ResourcesRoute
  ResultsRoute: typeof ResultsRoute
  WhyItKeepsComingBackRoute: typeof WhyItKeepsComingBackRoute
  AreasAreaSlugRoute: typeof AreasAreaSlugRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SolutionsFoodStorageRoute: typeof SolutionsFoodStorageRoute
  SolutionsGhostKitchensRoute: typeof SolutionsGhostKitchensRoute
  SolutionsHoasRoute: typeof SolutionsHoasRoute
  SolutionsMouseViolationsRoute: typeof SolutionsMouseViolationsRoute
  SolutionsPropertyManagersRoute: typeof SolutionsPropertyManagersRoute
  SolutionsResidentialRoute: typeof SolutionsResidentialRoute
  SolutionsRestaurantsRoute: typeof SolutionsRestaurantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-it-keeps-coming-back': {
      id: '/why-it-keeps-coming-back'
      path: '/why-it-keeps-coming-back'
      fullPath: '/why-it-keeps-coming-back'
      preLoaderRoute: typeof WhyItKeepsComingBackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/restaurants': {
      id: '/solutions/restaurants'
      path: '/solutions/restaurants'
      fullPath: '/solutions/restaurants'
      preLoaderRoute: typeof SolutionsRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/residential': {
      id: '/solutions/residential'
      path: '/solutions/residential'
      fullPath: '/solutions/residential'
      preLoaderRoute: typeof SolutionsResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/property-managers': {
      id: '/solutions/property-managers'
      path: '/solutions/property-managers'
      fullPath: '/solutions/property-managers'
      preLoaderRoute: typeof SolutionsPropertyManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/mouse-violations': {
      id: '/solutions/mouse-violations'
      path: '/solutions/mouse-violations'
      fullPath: '/solutions/mouse-violations'
      preLoaderRoute: typeof SolutionsMouseViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/hoas': {
      id: '/solutions/hoas'
      path: '/solutions/hoas'
      fullPath: '/solutions/hoas'
      preLoaderRoute: typeof SolutionsHoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ghost-kitchens': {
      id: '/solutions/ghost-kitchens'
      path: '/solutions/ghost-kitchens'
      fullPath: '/solutions/ghost-kitchens'
      preLoaderRoute: typeof SolutionsGhostKitchensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/food-storage': {
      id: '/solutions/food-storage'
      path: '/solutions/food-storage'
      fullPath: '/solutions/food-storage'
      preLoaderRoute: typeof SolutionsFoodStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$areaSlug': {
      id: '/areas/$areaSlug'
      path: '/areas/$areaSlug'
      fullPath: '/areas/$areaSlug'
      preLoaderRoute: typeof AreasAreaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  GetStartedRoute: GetStartedRoute,
  ResourcesRoute: ResourcesRoute,
  ResultsRoute: ResultsRoute,
  WhyItKeepsComingBackRoute: WhyItKeepsComingBackRoute,
  AreasAreaSlugRoute: AreasAreaSlugRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  SolutionsFoodStorageRoute: SolutionsFoodStorageRoute,
  SolutionsGhostKitchensRoute: SolutionsGhostKitchensRoute,
  SolutionsHoasRoute: SolutionsHoasRoute,
  SolutionsMouseViolationsRoute: SolutionsMouseViolationsRoute,
  SolutionsPropertyManagersRoute: SolutionsPropertyManagersRoute,
  SolutionsResidentialRoute: SolutionsResidentialRoute,
  SolutionsRestaurantsRoute: SolutionsRestaurantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
